openapi: 3.0.0
info:
  title: Credit Card Service API
  version: 1.0.0
  description: API documentation for the Credit Card Service in FinalticaPro

servers:
  - url: http://localhost:8082
    description: Local Development Server

paths:
  /creditcard/create:
    post:
      summary: Create a new credit card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Credit card created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCard'
        '400':
          description: Card already exists

  /creditcard/get/{id}:
    get:
      summary: Get credit card by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Credit card details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCard'
        '404':
          description: Card not found

  /creditcard/update/{id}:
    patch:
      summary: Update credit card details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCreditCardRequestDTO'
      responses:
        '200':
          description: Card updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCard'
        '404':
          description: Card not found

  /creditcard/delete/{id}:
    delete:
      summary: Delete a credit card
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Card deleted successfully
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Card not found

  /creditcard/validate:
    post:
      summary: Validate a transaction against credit card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateCardRequestDTO'
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Card not found

components:
  schemas:
    CreditCard:
      type: object
      properties:
        cardId:
          type: integer
        cardName:
          type: string
        cardType:
          type: string
        issuer:
          type: string
        creditLimit:
          type: number
          format: double
        totalSpent:
          type: number
          format: double
        billingDate:
          type: string
          format: date
        expiryDate:
          type: string
          format: date
        cardNumber:
          type: string
          description: Last 4 digits of the card
        userId:
          type: integer

    UpdateCreditCardRequestDTO:
      type: object
      properties:
        cardName:
          type: string
        cardType:
          type: string
        issuer:
          type: string
        creditLimit:
          type: number
          format: double
        totalSpent:
          type: number
          format: double
        billingDate:
          type: string
          format: date
        expiryDate:
          type: string
          format: date
        cardNumber:
          type: string

    ValidateCardRequestDTO:
      type: object
      properties:
        userId:
          type: integer
        cardId:
          type: integer
        amount:
          type: number
          format: double
